#get image name from docker hub
FROM jenkins/ssh-agent:latest-jdk17

#Install ca-certificates
RUN apt-get update && apt-get install -y ca-certificates

#install firefox
RUN apt-get install wget tar bzip2 libdbus-glib-1-2 -y
RUN wget -O firefox.tar.bz2 https://download-installer.cdn.mozilla.net/pub/firefox/releases/115.0/linux-x86_64/en-US/firefox-115.0.tar.bz2 \
  && tar xvjf firefox.tar.bz2 -C /opt/ \
  && rm firefox.tar.bz2 \
  && ln -s /opt/firefox/firefox /usr/local/bin/firefox

#Install chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && dpkg -i google-chrome*.deb || (apt-get update && apt-get install -f -y) \
  && rm -i google-chrome*.deb

#Install Ms Edge
RUN wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_114.0.1823.67-1_amd64.deb \
    && dpkg -i microsoft-edge*.deb || (apt-get update && apt-get install -f -y) \
    && rm -i microsoft-edge*.deb

# Download and extract maven to /opt directory and Set up the environment variables in maven.sh, Load the environment variables
RUN  apt install -y maven